# Notebook for wrapper functions that run calphy for given purpose

In [1]:
import calphy_interface as ci

## Structure and potential

In [2]:
from ase.build import bulk

Al_pure_structure = bulk('Al', cubic=True).repeat(3)

In [3]:
from pyiron_lammps import get_potential_by_name

potential_df = get_potential_by_name('2009--Mendelev-M-I--Al-Mg--LAMMPS--ipr1')
potential_df= potential_df.to_frame().transpose()
potential_df

/cmmc/ptmp/pyironhb/pyiron_latest_env/lib/python3.12/site-packages/pyiron_lammps/potential.py:324: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pot["Config"] = config_lst

,Config,Filename,Model,Name,Species,Citations
164,"[pair_style eam/fs, pair_coeff * * /cmmc/ptmp/...",[potential_LAMMPS/2009--Mendelev-M-I--Al-Mg--L...,NISTiprpy,2009--Mendelev-M-I--Al-Mg--LAMMPS--ipr1,"[Al, Mg]",[{'Mendelev_2009': {'title': 'Development of i...

## Running calphy

### Free energy at a particular temperature

In [4]:
input_params_fe = {  
    "mode": "fe", 
    "temperature": 300,  
    "n_equilibration_steps": 2500,
    "n_switching_steps": 2500,
    "n_print_steps": 1000,
    "equilibration_control": "nose-hoover",
    "queue": {
        "cores": 1,  
        "scheduler": "local"  
    },
    'reference_phase': 'solid',
    'file_format': 'lammps-data',
}

In [5]:
calphy_results_fe = ci.calc_free_energy_with_calphy(
    input_structure=Al_pure_structure,
    potential_df=potential_df,
    calphy_parameters=input_params_fe,
    working_directory='Aluminium_free_energy/Al_fe',
    user_dict={}
)

/cmmc/ptmp/pyironhb/pyiron_latest_env/lib/python3.12/site-packages/ase/io/lammpsdata.py:72: FutureWarning: "style" is deprecated; please use "atom_style".
  warnings.warn(
/cmmc/ptmp/pyironhb/pyiron_latest_env/lib/python3.12/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Unexpected Value)
  PydanticSerializationUnexpectedValue(Expected `list[float]` - serialized value may not be as expected [input_value=0, input_type=int])
  PydanticSerializationUnexpectedValue(Expected `list[list[float]]` - serialized value may not be as expected [input_value=0, input_type=int])
  return self.__pydantic_serializer__.to_python(

In [6]:
calphy_results_fe[0]

Calculation(monte_carlo=MonteCarlo(n_steps=1, n_swaps=0, forward_swap_types=[], reverse_swap_types=[], allow_all_swaps=True), composition_scaling=CompositionScaling(output_chemical_composition={}, restrictions=[]), md=MD(timestep=0.001, n_small_steps=10000, n_every_steps=10, n_repeat_steps=10, n_cycles=100, thermostat_damping=0.1, barostat_damping=0.1, cmdargs='', init_commands=[]), nose_hoover=NoseHoover(thermostat_damping=0.1, barostat_damping=0.1), berendsen=Berendsen(thermostat_damping=100.0, barostat_damping=100.0), queue=Queue(scheduler='local', cores=1, jobname='calphy', walltime='23:59:00', queuename='', memory='3GB', commands=[], options=[]), tolerance=Tolerance(lattice_constant=0.0002, spring_constant=0.1, solid_fraction=0.7, liquid_fraction=0.05, pressure=0.5), uhlenbeck_ford_model=UFMP(p=50.0, sigma=1.5), melting_temperature=MeltingTemperature(guess=None, step=200, attempts=5), materials_project=MaterialsProject(api_key='', conventional=True, target_natoms=1500), element=['Al', 'Mg'], n_elements=2, mass=[26.9815385, 1.0], kernel=0, inputfile='', mode='fe', lattice='/cmmc/u/pchilaka/1_Work/Packages/calphy_workflows/Aluminium_free_energy/Al_fe/fe-input_structure.data-solid-300-0.0.data', file_format='lammps-data', pressure=0, temperature=300.0, temperature_high=0.0, melting_cycle=True, pair_style=['eam/fs'], pair_coeff=['* * /cmmc/ptmp/pyironhb/pyiron_latest_env/share/iprpy/potential_LAMMPS/2009--Mendelev-M-I--Al-Mg--LAMMPS--ipr1/Al-Mg.eam.fs Al Mg'], potential_file=None, fix_potential_path=True, reference_phase='solid', lattice_constant=0, repeat=[1, 1, 1], script_mode=False, lammps_executable=None, mpi_executable=None, npt=True, n_equilibration_steps=2500, n_switching_steps=2500, n_print_steps=1000, n_iterations=1, equilibration_control='nose-hoover', folder_prefix=None, spring_constants=None, phase_name='', reference_composition=0.0)

In [7]:
calphy_results_fe[1]

,calculation_mode,status,temperature,pressure,free_energy,reference_phase,error_code,composition,calculation,ideal_entropy,reference_composition,Al,Mg
0,fe,True,300.0,0,-3.423951,solid,None,"{'Al': 1.0, 'Mg': 0.0}",Al_fe,0,0.0,1.0,0.0

### Temperature scaling

In [8]:
input_params_ts = {  
    "mode": "ts",
    "temperature": [300, 600],  
    "n_equilibration_steps": 2500,
    "n_switching_steps": 2500,
    "n_print_steps": 1000,
    "equilibration_control": "nose-hoover",
    "queue": {
        "cores": 1,  
        "scheduler": "local"  
    },
    'reference_phase': 'solid',
    'file_format': 'lammps-data',
}

In [9]:
calphy_results_ts = ci.calc_free_energy_with_calphy(
    input_structure=Al_pure_structure,
    potential_df=potential_df,
    calphy_parameters=input_params_ts,
    working_directory='Aluminium_free_energy/Al_ts',
    user_dict={}
)

/cmmc/ptmp/pyironhb/pyiron_latest_env/lib/python3.12/site-packages/ase/io/lammpsdata.py:72: FutureWarning: "style" is deprecated; please use "atom_style".
  warnings.warn(
/cmmc/ptmp/pyironhb/pyiron_latest_env/lib/python3.12/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Unexpected Value)
  PydanticSerializationUnexpectedValue(Expected `list[float]` - serialized value may not be as expected [input_value=0, input_type=int])
  PydanticSerializationUnexpectedValue(Expected `list[list[float]]` - serialized value may not be as expected [input_value=0, input_type=int])
  return self.__pydantic_serializer__.to_python(

In [10]:
calphy_results_ts[0]

Calculation(monte_carlo=MonteCarlo(n_steps=1, n_swaps=0, forward_swap_types=[], reverse_swap_types=[], allow_all_swaps=True), composition_scaling=CompositionScaling(output_chemical_composition={}, restrictions=[]), md=MD(timestep=0.001, n_small_steps=10000, n_every_steps=10, n_repeat_steps=10, n_cycles=100, thermostat_damping=0.1, barostat_damping=0.1, cmdargs='', init_commands=[]), nose_hoover=NoseHoover(thermostat_damping=0.1, barostat_damping=0.1), berendsen=Berendsen(thermostat_damping=100.0, barostat_damping=100.0), queue=Queue(scheduler='local', cores=1, jobname='calphy', walltime='23:59:00', queuename='', memory='3GB', commands=[], options=[]), tolerance=Tolerance(lattice_constant=0.0002, spring_constant=0.1, solid_fraction=0.7, liquid_fraction=0.05, pressure=0.5), uhlenbeck_ford_model=UFMP(p=50.0, sigma=1.5), melting_temperature=MeltingTemperature(guess=None, step=200, attempts=5), materials_project=MaterialsProject(api_key='', conventional=True, target_natoms=1500), element=['Al', 'Mg'], n_elements=2, mass=[26.9815385, 1.0], kernel=0, inputfile='', mode='ts', lattice='/cmmc/u/pchilaka/1_Work/Packages/calphy_workflows/Aluminium_free_energy/Al_ts/ts-input_structure.data-solid-300-0.0.data', file_format='lammps-data', pressure=0, temperature=[300.0, 600.0], temperature_high=0.0, melting_cycle=True, pair_style=['eam/fs'], pair_coeff=['* * /cmmc/ptmp/pyironhb/pyiron_latest_env/share/iprpy/potential_LAMMPS/2009--Mendelev-M-I--Al-Mg--LAMMPS--ipr1/Al-Mg.eam.fs Al Mg'], potential_file=None, fix_potential_path=True, reference_phase='solid', lattice_constant=0, repeat=[1, 1, 1], script_mode=False, lammps_executable=None, mpi_executable=None, npt=True, n_equilibration_steps=2500, n_switching_steps=2500, n_print_steps=1000, n_iterations=1, equilibration_control='nose-hoover', folder_prefix=None, spring_constants=None, phase_name='', reference_composition=0.0)

In [11]:
calphy_results_ts[1]

,calculation_mode,status,temperature,pressure,free_energy,reference_phase,error_code,composition,calculation,ideal_entropy,reference_composition,Al,Mg
0,fe,True,300.0,0,-3.423951,solid,None,"{'Al': 1.0, 'Mg': 0.0}",Al_fe,0,0.0,1.0,0.0
1,ts,True,"[300.0, 300.06001200240047, 300.1200480192077,...",0,"[-3.422420771033154, -3.4224394978711894, -3.4...",solid,None,"{'Al': 1.0, 'Mg': 0.0}",Al_ts,0,0.0,1.0,0.0